# .github/workflows/deploy-pb.yml
name: Deploy PB Hooks & Migrations

on:
  push:
    branches:
      - 'main'
      - 'staging'
  pull_request:
    branches:
      - 'main'
      - 'staging'

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy pb_hooks
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.PB_FTP_HOST }}
          username: ${{ secrets.PB_FTP_USERNAME }}
          password: ${{ secrets.PB_FTP_PASSWORD }}
          port: ${{ secrets.PB_FTP_PORT }}
          local-dir: packages/backend/pb_hooks/
          server-dir: settingly-${{ github.ref_name == 'main' && 'prod' || 'staging' }}/pb_hooks/
          state-name: pb-hooks-deploy 

      - name: Deploy pb_migrations
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.PB_FTP_HOST }}
          username: ${{ secrets.PB_FTP_USERNAME }}
          password: ${{ secrets.PB_FTP_PASSWORD }}
          port: ${{ secrets.PB_FTP_PORT }}
          local-dir: packages/backend/pb_migrations/
          server-dir: settingly-${{ github.ref_name == 'main' && 'prod' || 'staging' }}/pb_migrations/
          state-name: pb-migrations-deploy
