name: Deploy PB Hooks & Migrations

on:
  push:
    branches:
      - 'main'
    paths:
      - 'packages/backend/**'
  pull_request:
    branches:
      - 'main'
    paths:
      - 'packages/backend/**'

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy pb_hooks
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.PB_FTP_HOST }}
          username: ${{ secrets.PB_FTP_USERNAME }}
          password: ${{ secrets.PB_FTP_PASSWORD }}
          port: ${{ secrets.PB_FTP_PORT }}
          local-dir: packages/backend/pb_hooks/
          server-dir: settingly-${{ github.event_name == 'push' && 'production' || 'staging' }}/pb_hooks/
          state-name: pb-hooks-deploy 

      - name: Deploy pb_migrations
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.PB_FTP_HOST }}
          username: ${{ secrets.PB_FTP_USERNAME }}
          password: ${{ secrets.PB_FTP_PASSWORD }}
          port: ${{ secrets.PB_FTP_PORT }}
          local-dir: packages/backend/pb_migrations/
          server-dir: settingly-${{ github.event_name == 'push' && 'production' || 'staging' }}/pb_migrations/
          state-name: pb-migrations-deploy
